name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.19.0', 'latest']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Clean Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build --if-present

      - name: Run Tests
        run: npm test run

      - name: Run Tailwind Environment Tests
        run: npm test run -w 30 -w 3x -w 40 -w 4x
