name: Publish Package
on:
  release:
    types: [published]
jobs:
  npm:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node.js to Publish
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Publish to NPM Registry
        run: npm publish --access public

  github:
    name: Publish to GitHub Registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node.js to Publish
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jhadabora'

      - name: Set Scoped Package Name for GitHub Packages
        run: npm pkg set name=@jhadabora/$(node -p "require('./package.json').name")

      - name: Install Dependencies
        run: npm ci

      - name: Publish to NPM Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
